server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-customer
            uri: lb://ms-customer
            predicates:
              - Path=/api/v1/customers/**
          - id: ms-account
            uri: lb://ms-account
            predicates:
              - Path=/api/v1/accounts/**
          - id: ms-movements
            uri: lb://ms-account
            predicates:
              - Path=/api/v1/movements/**
          - id: ms-reports
            uri: lb://ms-account
            predicates:
              - Path=/api/v1/reports/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
